name: "Zeet Deploy"
description: "Deploy your Project with Zeet"
author: "Zeet"
inputs:
  api_url:
    description: "Zeet API Url"
    default: "https://anchor.zeet.co"
    required: false
  deploy_key:
    description: "Zeet deploy key"
    required: true
  project:
    description: "Zeet project name"
    required: false
  project_id:
    description: "Zeet project id"
    required: false
  image:
    description: "Docker image to deploy"
    required: false
  branch:
    description: "Branch name"
    required: false
  wait:
    description: "Wait till the deploy finishes"
    required: false
    default: "false"
  allow_prereleases:
    description: "If the latest version of the CLI is a prerelease, use it"
    required: false
    default: "false"
outputs:
  link:
    value: ${{ steps.main.outputs.link }}
    description: "Link to deployment"
runs:
  using: "composite"
  steps:
    - uses: zeet-dev/action-zeet@prereleases
      with:
        token: ${{ inputs.deploy_key }}
        api_url: ${{ inputs.api_url }}
        allow_prereleases: ${{ inputs.allow_prereleases }}
    - id: main
      uses: zeet-co/zeet-deploy-action/cli@v2
      with:
        project: ${{ inputs.project }}
        project_id: ${{ inputs.project_id }}
        image: ${{ inputs.image }}
        branch: ${{ inputs.branch }}
        wait: ${{ inputs.wait }}
