fragment DeployResult on Repo {
  id
  productionDeployment {
    id
  }
}

mutation UpdateProject($input: UpdateProjectInput!) {
  updateProject(input: $input) {
    ...DeployResult
  }
}

mutation DeployBranch($id: ID!, $branch: String) {
  buildRepo(id: $id, branch: $branch) {
    ...DeployResult
  }
}
