fragment DeployResult on Deployment {
  id
}

query GetProject($path: String!) {
  project(path: $path) {
    id
  }
}

mutation UpdateProject($input: UpdateProjectInput!) {
  updateProject(input: $input) {
    id
    productionDeployment {
      ...DeployResult
    }
  }
}

mutation UpdateBranch($input: UpdateBranchInput!) {
  updateBranch(input: $input) {
    id
    latestDeployment {
      ...DeployResult
    }
  }
}

mutation DeployBranch($id: ID!, $branch: String) {
  buildRepo(id: $id, branch: $branch) {
    id
    productionDeployment {
      ...DeployResult
    }
  }
}

query GetDeployment($id: ID!) {
  currentUser {
    id
    deployment(id: $id) {
      id
      status
    }
  }
}
